name: pipeline
on:
  push:
    branches:
      - master
      - beta
  workflow_dispatch:
    inputs:
      release:
        description: release
        required: true
        default: "true" 
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          docker-compose -f tasks/ci/docker-compose.yml build build
          docker-compose -f tasks/ci/docker-compose.yml run build
          docker-compose -f tasks/ci/docker-compose.yml down
      - name: publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          docker-compose -f tasks/ci/docker-compose.yml build publish
          docker-compose -f tasks/ci/docker-compose.yml run publish
          docker-compose -f tasks/ci/docker-compose.yml down
