name: pipeline
on:
  push:
    branches:
      - master
      - beta
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker-compose -f tasks/ci/docker-compose.yml build build
          docker-compose -f tasks/ci/docker-compose.yml run build
          docker-compose -f tasks/ci/docker-compose.yml down
      - name: deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker-compose -f tasks/ci/docker-compose.yml build deploy
          docker-compose -f tasks/ci/docker-compose.yml run deploy
          docker-compose -f tasks/ci/docker-compose.yml down
